apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: <SERVICE_NAME>
  name: <SERVICE_NAME>
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata: 
      labels:
        app: <SERVICE_NAME>
    spec:
      containers:
      - image: 192.168.1.27/devops/jenkins-demo:<BUILD_TAG>
        name: <SERVICE_NAME>
        ports:
        - name: web
          containerPort: 80
        resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 1000Mi
        livenessProbe:        
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 80
        
        readinessProbe:         
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 80


---

apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: <SERVICE_NAME>
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: web
    nodePort: 30003
    name: <SERVICE_NAME>

