apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <SERVICE_NAME>
  namespace: kube-ops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata: 
      labels:
        app: <SERVICE_NAME>
    spec:
      containers:
      - image: 192.168.1.27/devops/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: Always
        name: <SERVICE_NAME>
        resources: {}
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
