apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata: 
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: 192.168.1.27/devops/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: Always
        name: jenkins-demo
        resources: {}
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler 
