apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: <SERVICE_NAME>
  name: <SERVICE_NAME>
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata: 
      labels:
        app: <SERVICE_NAME>
    spec:
      containers:
      - image: 192.168.1.27/devops/<SERVICE_NAME>:<BUILD_TAG>
        name: <SERVICE_NAME>
        ports:
        - name: web
          containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: <SERVICE_NAME>
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: web
    nodePort: 30003
    name: <SERVICE_NAME>

